### PR TITLE
update range to accept -180 deg. give more information on fail

### PR DESCRIPTION
**Pull request by cipriangal**
small change in how we process the header for the magnetic field. The configuration before did not allow the map to start at -180 degrees.

### CODE REVIEW

**Comment by wdconinc** [comment]
Can we make the test inclusive of +180 deg too?

**Comment by cipriangal** [comment]
If I understand correctly how G4/remoll process fields, my only concern with that is that we could have -180 **and** 180 and then we have a "infinitesimally" small region of field doubling!?

**Comment by wdconinc** [comment]
My worry is that if we specify a field map from -180 to, say, +179 we will have a small region without field... :-)

I will have to look in more detail.

**Comment by cipriangal** [comment]
For the regions where we don't have a field (say between -180 and 179) the code interpolates afaik. We also use the 7 fold symmetry most of the time with these field maps.

**Comment by wdconinc** [comment]
I think this interpolation works exactly because of the n-fold symmetry (n gt 1). First the point is rotated to the 360/n extent around zero, then looked up in the map grid, which is by design larger than 360/n (it always prints a warning even). For n = 1 it will not do the rotation and doesn't know about the wrap around. That's what I remember. Been a while I looked in that code.

**Comment by rahmans1** [comment]
Just wanted to mention that I did assume that it generalises to n=1. I haven’t looked too deeply into the code either.

**Comment by wdconinc** [comment]
There's indeed a gap between -180 and +177 degrees. Here are values at the phi = 90*k +/- epsilon with the "symmetric" fieldmap:
```
At r(0.00037,0.014,9.55) [m]: B = -6.25988e-12 1.03429e-13 -8.50884e-16 T
At r(0.00037,-0.014,9.55) [m]: B = 6.25988e-12 1.03433e-13 8.50634e-16 T
At r(0.014,0.00037,9.55) [m]: B = -8.5734e-14 5.98926e-12 -6.10655e-13 T
At r(-0.014,0.00037,9.55) [m]: B = -1.85002e-13 -6.23779e-12 8.36787e-17 T
At r(-0.00037,0.014,9.55) [m]: B = -6.22348e-12 -2.13503e-13 -2.27239e-16 T
At r(-0.00037,-0.014,9.55) [m]: B = 6.22348e-12 -2.13502e-13 2.27465e-16 T
At r(0.014,-0.00037,9.55) [m]: B = 0 0 0 T
At r(-0.014,-0.00037,9.55) [m]: B = 1.85007e-13 -6.2378e-12 -8.35279e-17 T
```

For comparison here's the phi = 90*k equivalent in the default -25 to +25 deg maps:
```
At r(0,0.16,9.55) [m]: B = -5.04231e-11 4.75071e-12 4.27685e-12 T
At r(0,-0.16,9.55) [m]: B = 5.04231e-11 4.75072e-12 -4.27685e-12 T
At r(0.16,0,9.55) [m]: B = 0 0 0 T
At r(-0.16,0,9.55) [m]: B = 3.19205e-18 -5.64926e-11 -2.30044e-18 T
```
but we know that we are missing a part there...

You can get this output with
```
build/remoll macros/tests/unit/test_fields.mac
```
after removing the comment characters there.

@cipriangal This means that field maps have to either specify the +180 degrees points as well (they are identical to the -180 degrees points) or we have to make the code smarter so it knows it's a periodic coordinate.

**Comment by wdconinc** [comment]
@cipriangal I started fixing this in the code, but it essentially becomes a fix for only this particular field map. I think it would be better to regenerate the field map to not have a gap between -180 and +180 degrees.

**Comment by wdconinc** [comment]
```
#!/bin/bash

head -n 6 $1
{
  tail -n +7 $1
  tail -n +7 $1 | awk -v OFS="\t" '{ if ($2==-180) { $2=180; print($0) } }'
} | sort -n -k3,3 -k2,2 -k1,1
```

**Comment by cipriangal** [comment]
@rahmans1 : I think @wdconinc is right here. We should probably just set a particular definition for how we export files from TOSCA and have only one implementation. Could you get the offset and symmetric maps to not have a gat between -180 and 180?

**Comment by wdconinc** [comment]
I can upload the field maps with the additional lines added to the moller web location. I'll just call them 0.1 instead of 0.0 (assuming that was supposed to be a version number...).

**Comment by wdconinc** [comment]
(I'm referring to those listed here: https://hallaweb.jlab.org/12GeV/Moller/downloads/remoll/)

**Comment by wdconinc** [comment]
Updated map with that snippet gives me:
```
G4WT0 > At r(0.00037,0.014,9.55) [m]: B = -6.25988e-12 1.03429e-13 -8.50884e-16 T
G4WT0 > At r(0.00037,-0.014,9.55) [m]: B = 6.25988e-12 1.03433e-13 8.50634e-16 T
G4WT0 > At r(0.014,0.00037,9.55) [m]: B = -8.5734e-14 5.98926e-12 -6.10655e-13 T
G4WT0 > At r(-0.014,0.00037,9.55) [m]: B = -1.85002e-13 -6.23779e-12 8.36787e-17 T
G4WT0 > At r(-0.00037,0.014,9.55) [m]: B = -6.22348e-12 -2.13503e-13 -2.27239e-16 T
G4WT0 > At r(-0.00037,-0.014,9.55) [m]: B = 6.22348e-12 -2.13502e-13 2.27465e-16 T
G4WT0 > At r(0.014,-0.00037,9.55) [m]: B = 8.5729e-14 5.98926e-12 6.10655e-13 T
G4WT0 > At r(-0.014,-0.00037,9.55) [m]: B = 1.85007e-13 -6.2378e-12 -8.35279e-17 T
```
so it does not have the gap.

**Comment by rahmans1** [comment]
@wdconinc The reason why I avoided generating between -180 to 180 was I thought the magnetic field is added cumulatively in overlapping regions. However, it would only be the case for that one point I guess... so negligible effect? Simple fix would be to just add an extra line for theta =180 field value that has the same value as theta=-180 for each z-coordinate which you have already done it seems....

**Comment by wdconinc** [comment]
The field will not double-count itself even if it wraps around several times in azimuth (but if you load multiple fields defined in the same region of space they will add up). You could theoretically define a field map with a phi grid between 0 and 720 degrees (maybe for a spin 1/2 field?) and it would still return the value (in this case the appropriate value between 0 and 360 degrees).

I have indeed added the lines for +180 equal to those for -180, resorted the file, and fixed the header to reflect this. I don't have other maps, but if you do you should be able to fix them with that little bit of code too.

**Comment by wdconinc** [comment]
Uploaded to https://hallaweb.jlab.org/12GeV/Moller/downloads/remoll/. Will update CMakeLists.txt to refer to those (with correct MD5). Will update remollMagneticField to complain about these kind of gaps in the field.

The problem is primarily that this is right in the middle of an open sector :-)

**Comment by rahmans1** [comment]
@wdconinc Thanks. Sounds reasonable to me.

**Pull request merged**
