### PR TITLE
Feature: remove old geometry mothers

### PR DESCRIPTION
**Pull request by wdconinc**
We currently have the following "mother" geometries in the geometry directory.
- [x] geometry/mollerMother_5open.gdml
- [x] geometry/mollerMother_acceptanceDefinition.gdml
- [x] geometry/mollerMother_acceptanceDefinition_includeCol4.gdml
- [x] geometry/mollerMother_black.gdml
- [ ] geometry/mollerMother_Clamshell_Optimized.gdml
- [x] geometry/mollerMother_dump.gdml
- [x] geometry/mollerMother.gdml
- [x] geometry/mollerMother_merged.gdml
- [ ] geometry/mollerMother_noShlds.gdml
- [x] geometry/mollerMother_parametrized.gdml
- [x] geometry/mollerParallel.gdml
The large number causes confusion, in particular since `mollerMother.gdml` is typically not the one to use.

This PR removes the following geometries (old terminology):
- [X] geometry/mollerMother.gdml
- [X] geometry/mollerMother_dump.gdml
and renames the following geometries:
- [X] geometry/mollerMother_merged.gdml -> geometry/mollerMother.gdml

### CODE REVIEW

**Comment by cameronc137** [comment]
black and 5open are detector array geometries, and the acceptance definition ones are intermediate steps (just commenting out collimators 4 and 5) for generating electron envelopes and deciding new collimator sculpts (which are now stale after Chandan's new work on this)

**Comment by wdconinc** [comment]
@cameronc137 so, which ones can be deleted?

**Comment by cameronc137** [comment]
These can be deleted:
 geometry/mollerMother_5open.gdml
￼ geometry/mollerMother_acceptanceDefinition.gdml
￼ geometry/mollerMother_acceptanceDefinition_includeCol4.gdml
￼ geometry/mollerMother_black.gdml

**Comment by wdconinc** [comment]
What about the following ones, @cameronc137 ?
- [ ] ￼geometry/mollerMother_Clamshell_Optimized.gdml
- [ ] geometry/mollerMother_noShlds.gdml

You created both of them. Are they still useful?

**Pull request merged**
