### PR TITLE
Fixing optical physics by demoting parallel world physics list to the…

### PR DESCRIPTION
**Pull request by cameronc137**
I think this fixes issue #158 but it may break parallel world physics.

Commenting out line 63 in src/remollDetectorConstruction.cc is most likely irrelevant and probably should get put back in...

### CODE REVIEW

**Comment by cameronc137** [comment]
@rakithab can you check to see if this change has any affect on the neutron hits bug that you were seeing the other day?

**Comment by cameronc137** [comment]
@wdconinc - Unfortunately my approach to fixing this issue by making parallel world physics optional does not fix the problem that optical physics breaks when parallel physics is enabled. This means that the pion_optical_response.mac macro is broken and cannot work (though it was already broken before I tried fixing things anyway).

What should we do? Allow parallel physics to break optical, or see if there is some more detailed solution and try to make them work simultaneously?

Also, Rakitha found his bug with the neutrons, and it was due to some other gdml issue (though I still don't quite understand why only he was seeing the problem).

**Comment by wdconinc** [comment]
Who do you say that pion_optical_response.mac is broken and cannot work? I have a student looking at data generated from that macro that has both optical photons and hits on detector 28...

**Comment by wdconinc** [comment]
I am fine with getting rid of parallel world, but that means no more detector 28 or other virtual planes. The parallel world was a way to keep those around while we implement detailed material geometry.

**Comment by cameronc137** [comment]
Yes, optical photons still work, but the reflectivity properties were messed up. It would be worthwhile to check that your simulation is treating the photons the same with and without the parallel world physics list enabled.

**Comment by cameronc137** [comment]
Do the physics lists need to be put after /run/initialize or before?

**Comment by wdconinc** [comment]
@cameronc137 can this branch bugfix-opticalReflections-fix be deleted? It is fully merged and we are tracking the optical<>parallel issues in #158 and develop branch.

**Pull request merged**
