### PR TITLE
Merge integration dose into develop

### PR DESCRIPTION
**Pull request by wdconinc**
This includes a sanitized :-) version of the dose branch. Someone familiar with the dose branch (@cameronc137 @rakithab) will want to expect some more questions on geometry differences in this thread. Some stuff seems to have changed between dose and develop in relevant geometry files.

### CODE REVIEW

**Comment by wdconinc** [comment]
What should radius_of_cylwall be?
```
diff --git a/geometry_sculpt_less_hybshld/hallDaughter.gdml b/geometry/hallDaughter_merged.gdml
similarity index 98%
rename from geometry_sculpt_less_hybshld/hallDaughter.gdml
rename to geometry/hallDaughter_merged.gdml
index ec8056f..0592647 100644
--- a/geometry_sculpt_less_hybshld/hallDaughter.gdml
+++ b/geometry/hallDaughter_merged.gdml
@@ -20,7 +20,7 @@
   <constant name="thick_wall" value="1547.76"/> 
   <constant name="center_wall" value="radius_of_hall+thick_wall/2"/>      Not in use anymore -->
 
-  <constant name="radius_of_cylwall" value="25460."/>
+  <constant name="radius_of_cylwall" value="26517.6"/><!--25460."/>-->
   <constant name="thick_cylwall" value="1487."/>  
   <constant name="height_cylwall" value="17770."/>
   <constant name="bottom_cylwall" value="-4470."/>  
```

**Comment by wdconinc** [comment]
Anyway, here's the full list of relevant diffs: [dose_develop.diff](https://gist.github.com/wdconinc/5a7dd132c65cf957f00a9e9136adc602)

**Comment by cameronc137** [comment]
That depends on whether or not we want to keep the commit tracking alive. That would require merging the geometry files I worked on in the sbujlab local fork of the dose branch to include those updates, but otherwise the files in the geometry folder of JeffersonLab/remoll/develop do reflect my most up to date files and are the ones I have worked on since their inclusion in there.

**Comment by wdconinc** [comment]
Lots of trivial stuff is stripped out of that already (added files, removed files, sensitive detector lines, stuff I don't have any questions about).

**Comment by wdconinc** [comment]
Ok, then I'm just going to make sure that any merge from integration-dose into develop will not touch those at all. We can then take it from there. History will be maintained if we do a proper merge instead of just dropping the branch, even if at some future point we git rm the files.

**Comment by wdconinc** [comment]
Down to the following merge differences in geometry/:
```
diff --git a/../remoll_develop/geometry/dumpDaughter.gdml b/geometry/dumpDaughter.gdml
index 8f787c9..4365f21 100644
--- a/../remoll_develop/geometry/dumpDaughter.gdml
+++ b/geometry/dumpDaughter.gdml
@@ -71,8 +73,8 @@
 
     <constant name="thick_floor" value="50.0"/>
     <constant name="width_floor" value="2000.0"/>
-    <constant name="length_floor" value="(center_wall+thick_wall/2-(prex_target_center-deltaz_sc-outer_r_sc))"/>
-    <constant name="floor_z_center" value="length_floor/2+(prex_target_center-deltaz_sc-outer_r_sc)"/>
+    <!-- <constant name="length_floor" value="(center_wall+thick_wall/2-(prex_target_center-deltaz_sc-outer_r_sc))"/> -->
+    <!-- <constant name="floor_z_center" value="length_floor/2+(prex_target_center-deltaz_sc-outer_r_sc)"/> -->
     <constant name="floor_y_center" value="(-height_wall-thick_floor)/2"/>
 
     <constant name="width_dump" value="600.0"/>
@@ -120,7 +122,7 @@
     <constant name="dumpExt_length" value="1335.0875 - 450.0 + 135.0 - 20.0"/>
     <constant name="dumpExt_offset" value="0"/>
     <constant name="dumpExt_center_z" value="hall_cylwall_radius - dumpExt_length/2 - dumpExt_offset"/>
-    <position unit="cm" name="dumpExt_trans" x="0" y="0" z="tempdet_center_z - hall_cylwall_radius + dumpExt_length/2 + dumpExt_offset"/> 
+    <!-- <position unit="cm" name="dumpExt_trans" x="0" y="0" z="tempdet_center_z - hall_cylwall_radius + dumpExt_length/2 + dumpExt_offset"/> -->
 
     <!-- Dump --> 
 
@@ -250,7 +252,7 @@
     <position unit="cm" name="targ_center" x="0" y="0" z="center_targ"/>
     <position unit="cm" name="crex_targ_center" x="0" y="0" z="crex_target_center"/>
 
-    <position unit="cm" name="tempdet_position" x="0" y="0" z="tempdet_center_z"/>
+    <!-- <position unit="cm" name="tempdet_position" x="0" y="0" z="tempdet_center_z"/> -->
     <position unit="cm" name="hall_top_center" x="0" y="hall_top_center_y" z="0"/>
     <position unit="cm" name="hall_cylwall_center" x="0" y="hall_cylwall_center_y" z="0"/>
     <position unit="cm" name="hall_floor_center" x="0" y="hall_floor_center_y" z="0"/>
@@ -324,11 +326,13 @@
 
     <tube aunit="deg" startphi="0" deltaphi="360" lunit="cm" name="dumpExt_1" rmin="dumpExt_r_min" rmax="dumpExt_r_max" z="dumpExt_length"/>
 
+    <!--
     <subtraction name ="dumpExt_solid">
       <first ref="dumpExt_1"/>
       <second ref="tempdet_solid"/>
       <positionref ref="dumpExt_trans"/>
     </subtraction>
+    -->
 
   <!-- Dump Enclosure -->
 
@@ -519,6 +523,7 @@
       <auxiliary auxtype="DetNo" auxvalue="8"/>
     </volume>
 
+    <!--
     <volume name="dumpExt_logic">
       <materialref ref="Aluminum"/>
       <solidref ref="dumpExt_solid"/>
@@ -526,6 +531,7 @@
       <auxiliary auxtype="SensDet" auxvalue="DumpExt"/>
       <auxiliary auxtype="DetNo" auxvalue="51"/>
     </volume>
+    -->
     
     <volume name="dump_logic">
       <materialref ref="Concrete"/>
diff --git a/../remoll_develop/geometry/hallDaughter_merged.gdml b/geometry/hallDaughter_merged.gdml
index 1442849..0592647 100644
--- a/../remoll_develop/geometry/hallDaughter_merged.gdml
+++ b/geometry/hallDaughter_merged.gdml
@@ -20,7 +20,7 @@
   <constant name="thick_wall" value="1547.76"/> 
   <constant name="center_wall" value="radius_of_hall+thick_wall/2"/>      Not in use anymore -->
 
-  <constant name="radius_of_cylwall" value="25460."/>
+  <constant name="radius_of_cylwall" value="26517.6"/><!--25460."/>-->
   <constant name="thick_cylwall" value="1487."/>  
   <constant name="height_cylwall" value="17770."/>
   <constant name="bottom_cylwall" value="-4470."/>  
diff --git a/../remoll_develop/geometry/mollerMother_noShlds.gdml b/geometry/mollerMother_noShlds.gdml
index e00e739..8c28603 100644
--- a/../remoll_develop/geometry/mollerMother_noShlds.gdml
+++ b/geometry/mollerMother_noShlds.gdml
@@ -30,32 +30,32 @@

       <physvol>
-      <file name="geometry/hallDaughter_merged.gdml"/>
-      <positionref ref="hallCenter"/>
-      <rotationref ref="identity"/>
+        <file name="hallDaughter_noShlds.gdml"/>
+        <positionref ref="hallCenter"/>
+        <rotationref ref="identity"/>
       </physvol>
 
       <physvol>
-      <file name="geometry/detectorDaughter_merged.gdml"/>
-      <positionref ref="detectorCenter"/>
-      <rotationref ref="identity"/>
+        <file name="detectorDaughter_noShlds.gdml"/>
+        <positionref ref="detectorCenter"/>
+        <rotationref ref="identity"/>
       </physvol>
 ```
Questions:
1. dumpExt_solid included or not?
2. radius_of_cylwall which value?
3. mollerMother_noShlds: include hallDaughter_merged or hallDaughter_noShlds, same for detectorDaughter?

**Comment by cameronc137** [comment]
For 1) The dump extension beampipe is for prex, but it will be removed for MOLLER, so no (and a number of other elements of the dump are prex specific, like the entire telescoping beampipe at the front of the hall and probably the donut, which is an approximation in the first place).

For 2) The cylwall radius is likely the larger one, but I need confirmation from someone who knows the blueprints for hall A

For 3) The naming convention is a good question. When I run ifarm simulations I like to keep all of the related files consistent with suffixes, but I also like to change the suffixes whenever some parameter changes. So probably we need to stop proliferating suffixes and incorporate a more intelligent way to have a baseline geometry and also have new versions with slight tiny changes to parameters as they are tested in ifarm simulations. @cipriangal may have better ideas for how to do this.

**Comment by wdconinc** [comment]
Nevermind, these were diffs with respect to master, so:
1. dumpExt_solid is already disabled in develop
2. cylwall radius is already the larger on in develop
3. noShlds already includes noShlds files, not merged files, in develop

**Comment by cipriangal** [comment]
@wdconinc, @cameronc137 : here is a drawing of the hall (as built - as far as I know):
https://prex.jlab.org/DocDB/0002/000207/001/Scans4865.pdf

In it you should see that the hall is about 26.5 m in radius.

**Comment by cipriangal** [comment]
For the naming conventions I really don't have a smart way to not proliferate files with different _subNames 

I think we can do two things: 
a) when we run on the farm we have to make a tarball with the needed geometry anyway so when we put results somewhere (on an elog) we add the tarball.
b) when we finish a study we can mark it with a small number release .. say v.X.Y.Z where Z is the release for this study. after which we can just clean up the files that are no longer needed (say you tested 10 hall radii and you settled on the 3rd one -> rename that to the default and remove the rest). If anyone wants to reproduce your test they can either get the geometry from the tarball on the elog or go the the Z release and run there.

This is not the greatest plan but at least we can ensure that things are easily reproducible later (which to me is the most important thing).

**Comment by wdconinc** [comment]
Every simulation contains the full gdml geometry as part of the root file, so we have that. Commit hash is stored for remoll.

Next step is geometry into separate repo for tracking and branching. That should alleviate filename issues through branching. I won't be as strict on the merging there ;-)

**Comment by cipriangal** [comment]
Actually I am not sure that will work since the run_data only lists (as far as I can tell) the geometry files and will tell you if they have any changes compared to the commit hash. So in the case that someone runs a bunch of jobs with a change that is not in a commit we cannot recover that. @wdconinc : am i wrong?

**Comment by wdconinc** [comment]
The full gdml content is stored, not just the name. Not sure how easily one can write it out but there's a function for it somewhere. Let me see...

**Comment by wdconinc** [comment]
remollRunData::RecreateGDML

**Comment by wdconinc** [comment]
```
14:53:16 wdconinc@parity ~/git/remoll $ build/reroot remollout.root 
   ------------------------------------------------------------                                                                                                                   
  | Welcome to ROOT 6.14/00                http://root.cern.ch |                                                                                                                  
  |                               (c) 1995-2018, The ROOT Team |                                                                                                                  
  | Built for linuxx8664gcc                                    |                                                                                                                  
  | From tag v6-14-00, 13 June 2018                            |                                                                                                                  
  | Try '.help', '.demo', '.license', '.credits', '.quit'/'.q' |                                                                                                                  
   ------------------------------------------------------------                                                                                                                   
                                                                                                                                                                                  
re-root [0]                                                                                                                                                                       
Attaching file remollout.root as _file0...                                                                                                                                        
(TFile *) 0x1f7c280                                                                                                                                                               
re-root [1] run_data->RecreateGDML("/tmp")
Recreating mollerMother.gdml                                                                                                                                                      
Recreating targetDaughter.gdml                                                                                                                                                    
Recreating detectorDaughter.gdml                                                                                                                                                  
Recreating trackingDaughter.gdml                                                                                                                                                  
Recreating pionDetectorSystem.gdml                                                                                                                                                
Recreating pionDetectorVirtualDet.gdml                                                                                                                                            
Recreating pionDetectorTSOpenSector.gdml                                                                                                                                          
Recreating pionDetectorTS.gdml                                                                                                                                                    
Recreating pionDetectorGEMOpenSector.gdml                                                                                                                                         
Recreating pionDetectorGEM.gdml                                                                                                                                                   
Recreating pionDetectorLuciteSector.gdml                                                                                                                                          
Recreating pionDetectorLucite.gdml                                                                                                                                                
Recreating pionDetectorCalorimeter.gdml                                                                                                                                           
Recreating upstreamDaughter.gdml
Recreating hybridDaughter.gdml
re-root [2] .q
```

**Comment by wdconinc** [comment]
(Needs to be done with either reroot or with LD_PRELOADed libremoll.so so you have the RecreateGDML function that does this.)

**Comment by cipriangal** [comment]
I didn't know about this. That is perfect.

**Pull request merged**
