### PR TITLE
Merge feature-sums-refactor branch into develop

### PR DESCRIPTION
**Pull request by wdconinc**
This seems to work fine now on the #172 test case.

For an electron hitting lead, only a subset of hits are stored (those with > 0.1 MeV energy, for example) but all are included in the sums. The pids 1000822060 and 1000822080 are lead 206 and 208 nuclei (see http://pdg.lbl.gov/2017/reviews/rpp2017-rev-monte-carlo-numbering.pdf if you are curious).
```
Lead
hit: 2.79084 0.250722 0.126983 0.751546 0.689868 0.136596 0.169301 1.72661 0.695538 0.00539331 0.232751 0.0403262 0.136237 0.624287 0.344374 0.638755 0.684848 0.231549 0.831656 1.49825 0.16947 0.233465 0.031472 0.214394 0.572451 0.593841 0.919408 0.0527639 0.66293 0.281838 0.386466 0.69345 0.653826 0.206384 0.727071 0.923065 1.09825 3.8036 0.773688 1.65728 4.2843 1.58518 0.969855 1.89878 2.54394 3.02038 0.554339 MeV
hit sum = 42.1183 MeV
sum: 10971.5 MeV
sum [pid = -11]: 3229.72 MeV
sum [pid = 11]: 7339.18 MeV
sum [pid = 22]: 402.575 MeV
sum [pid = 1000822060]: 0.00104249 MeV
sum [pid = 1000822080]: 0.00179189 MeV
Krypt
hit: 10999.5 MeV
hit sum = 10999.5 MeV
sum: 10999.5 MeV
sum [pid = 11]: 10999.5 MeV
```

### CODE REVIEW

**Comment by wdconinc** [comment]
Though I probably should revisit that online updating weighted position average...
```
Lead
hit: 2.79084 0.250722 0.126983 0.751546 0.689868 0.136596 0.169301 1.72661 0.695538 0.00539331 0.232751 0.0403262 0.136237 0.624287 0.344374 0.638755 0.684848 0.231549 0.831656 1.49825 0.16947 0.233465 0.031472 0.214394 0.572451 0.593841 0.919408 0.0527639 0.66293 0.281838 0.386466 0.69345 0.653826 0.206384 0.727071 0.923065 1.09825 3.8036 0.773688 1.65728 4.2843 1.58518 0.969855 1.89878 2.54394 3.02038 0.554339 MeV
hit sum = 42.1183 MeV
sum: 10971.5 MeV
sum [pid = -11]: 3229.72 MeV at (0.0575065, 0.604554, -207.973) mm 
sum [pid = 11]: 7339.18 MeV at (0.00115157, 0.308734, -203.499) mm 
sum [pid = 22]: 402.575 MeV at (-nan, -nan, -nan) mm 
sum [pid = 1000822060]: 0.00104249 MeV at (-10.4974, -1.36693, -188.787) mm 
sum [pid = 1000822080]: 0.00179189 MeV at (-11.3404, 2.37085, -205.098) mm 
```

**Comment by wdconinc** [comment]
Better now.
```
Lead
hit: 2.79084 0.250722 0.126983 0.751546 0.689868 0.136596 0.169301 1.72661 0.695538 0.00539331 0.232751 0.0403262 0.136237 0.624287 0.344374 0.638755 0.684848 0.231549 0.831656 1.49825 0.16947 0.233465 0.031472 0.214394 0.572451 0.593841 0.919408 0.0527639 0.66293 0.281838 0.386466 0.69345 0.653826 0.206384 0.727071 0.923065 1.09825 3.8036 0.773688 1.65728 4.2843 1.58518 0.969855 1.89878 2.54394 3.02038 0.554339 MeV
hit sum = 42.1183 MeV
sum: 10971.5 MeV
sum [pid = -11]: 3229.72 MeV at (0.0575065, 0.604554, -207.973) mm 
sum [pid = 11]: 7339.18 MeV at (0.00115157, 0.308734, -203.499) mm 
sum [pid = 22]: 402.575 MeV at (0.00941529, 0.530072, -202.845) mm 
sum [pid = 1000822060]: 0.00104249 MeV at (-10.4974, -1.36693, -188.787) mm 
sum [pid = 1000822080]: 0.00179189 MeV at (-11.3404, 2.37085, -205.098) mm 
```

**Comment by wdconinc** [comment]
@cameronc137 this is ready to merge when you think this is ready.

**Comment by wdconinc** [comment]
Yeah, we should merge this. 50k moller events generates a 6.4Gb ROOT file now... That's a bit much.

**Comment by cameronc137** [comment]
Ok, it looks good. Does this still rely on the addedep or getedep (I don't remember which) getting called in the post event IO place?

**Comment by wdconinc** [comment]
AddEdep is called in the detector's ProcessHits, but nothing is called from remollIO.

**Comment by wdconinc** [comment]
I'm just trying to run 50k events in this branch to see if it actually decreases tree size substantially... Then I might just click the button.

**Comment by wdconinc** [comment]
50k moller events generates 593M in this branch....

**Pull request merged**
