### PR TITLE
Feature change magnet z offset

### PR DESCRIPTION
**Pull request by rahmans1**
With this pull request, all prior field maps will be unusable as default since they use the old target center (5m upstream of hall center) as reference. New field maps will be provided that use the hall center as reference 0.

### CODE REVIEW

**Comment by wdconinc** [comment]
We can still set the offset for old field maps in a macro. We should include these instructions.

**Comment by wdconinc** [comment]
In general, if an old code continues to run it should be correct. If it can't be made correct, it should crash until the user fixes the issue. We don't want users to run with old field maps and get wrong results without realizing it.

**Comment by rahmans1** [comment]
> We can still set the offset for old field maps in a macro. We should include these instructions.

That's true. We will probably settle on new magnet designs very soon. However, if people want to have access to the current maps for archival purposes, i will write up the instructions on how to do that.

**Comment by wdconinc** [comment]
Merged into #414

**Pull request closed without merging**
