### PR TITLE
Feature shield design

### PR DESCRIPTION
**Pull request by cipriangal**
update develop to shielding configuration 23. Fix overlaps and update shielding.

### CODE REVIEW

**Comment by cipriangal** [comment]
When you do approve this pull request please keep the feature branch so we can continue work from it.

**Review by rahmans1 — APPROVED** [review]
Ran some comparisons with an old version of radial distributions https://moller.jlab.org/cgi-bin/DocDB/private/ShowDocument?docid=865 (slide 4 and 5). Seems ok to merge.

**Comment by wdconinc** [comment]
I know you want me to approve this pull request and merge it. But there are too many changes in this pull request for any meaningfull approval process. I don't feel comfortable just saying approve.

**Comment by rakithab** [comment]
Feature shield design. I'm merging the Feature shield design into the development branch. There is a docker image error that I don't know what to do.

**Pull request merged**
