### PR TITLE
Feature: add only SBS bunker

### PR DESCRIPTION
**Pull request by wdconinc**
Per #291 [comment](https://github.com/JeffersonLab/remoll/pull/291#issuecomment-642852430) this merges just the SBS bunker into develop, none of the other stuff in feature-add-SBSbunker.

### CODE REVIEW

**Comment by wdconinc** [comment]
Trivial conflict resolved.

**Comment by chandabindu** [comment]
I am sure that the positions is with respect to old origin (wrt to target center). We have to change the position for the new origin (wrt hall center)..

**Comment by wdconinc** [comment]
Good point. Seem z is 15180 mm upstream of hall center.

**Comment by wdconinc** [comment]
image

**Pull request merged**
